import type { NextPage } from "next";
import Head from "next/head";
import { v4 } from "uuid";
import MainLayout from "../components/layouts/MainLayout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>LivingIdea</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div>Hello</div>
      </MainLayout>
    </div>
  );
};

export default Home;
